#!/bin/sh

rootfs=buildroot

[ $(whoami) = "root" ] || exec unshare --mount --map-root-user $0 $@

for m in /proc /sys /dev; do
	mount --rbind $m $rootfs/$m
done

for m in src conf out; do
	mount --bind $m $rootfs/build/$m
done

if [ "$1" = "build" ]; then
	shift
	set -- /build/conf/build $@
fi

export sysroot=/build/sysroot
export PATH=$PATH:$sysroot/bin
export PKG_CONFIG_PATH=$sysroot/lib/pkgconfig
export HOME=/root
chroot $rootfs "$@"
ret=$?

# unmounting not needed as new mountpoints are automatically destroyed
# as soon as we leave the mount namespace

[ $ret -ne 0 ] && echo "chroot: exit status $ret"
exit $ret
