#!/bin/sh

dev=wlan0
ip_addr=192.168.178.48/24
gateway=192.168.178.1

wpa_supplicant -B -s -i $dev -c /etc/wpa_supplicant.conf
ip link set up dev lo
ip addr add $ip_addr dev $dev
ip route add default via $gateway dev $dev
