#!/bin/bash

set -e

usage() {
	echo "Usage: $(basename $0) <target>"
	exit 1
}

download() {
	cd /build/src
	mkdir -p download
	for url in $@; do
		file=$(basename $url)
		[ -f download/$file ] || curl -L $url -o download/$file
	done
}

gpg_verify() {
	file=$1
	sig=$2
	pubkey=$3

	gpg --recv-keys $pubkey
	gpg --verify $sig $file
	for p in dirmngr keyboxd gpg-agent; do pkill $p; done || true
}

bininst() {
	# automatically finds all libraries the binaries depend on, and installs both
	# the binaries and their libraries into the initramfs
	for bin in $@; do
		libs=$(printf "%s\n" $libs $(chroot $sysroot ldd /bin/$bin |
			awk '$1 !~ /ld-musl-/ {print $1}') )
	done
	libs=$(echo "$libs" | sort | uniq)
	for bin in $@; do install -s $sysroot/bin/$bin $ramfs_dir/bin; done
	for lib in $libs; do install -s $sysroot/lib/$lib $ramfs_dir/lib; done
}

build_musl() {
	version=v0.9.11
	url=https://github.com/richfelker/musl-cross-make.git
	dir=musl-cross-make-$version

	cd /build/src
	[ -d $dir ] && rm -rf $dir
	
	git clone $url $dir
	cd $dir
	git checkout $version
	make TARGET=x86_64-linux-musl -j$(nproc)
	mkdir -p $sysroot/{bin,lib}
	ln -sf bin $sysroot/sbin
	ln -sf lib $sysroot/lib64
	ln -sf . $sysroot/usr
	ln -sf . $sysroot/x86_64-linux-musl
	ln -sf ../lib/libc.so $sysroot/bin/ldd
	make TARGET=x86_64-linux-musl OUTPUT=$sysroot install
	# musl-cross-make links this to /lib/libc.so which breaks key conversion in build_dropbear()
	ln -sf libc.so $sysroot/lib/ld-musl-x86_64.so.1
}

build_busybox() {
	version=1.36.1
	url=https://busybox.net/downloads
	archive=busybox-$version.tar.bz2
	dir=${archive%.tar.bz2}

	cd /build/src

	if [ "$1" = "configure" ]; then
		cd $dir
		make menuconfig
		cp .config /build/conf/busybox.config
	else
		download $url/$archive
		[ -d $dir ] && rm -rf $dir
		tar -xf download/$archive
		cd $dir
		cp /build/conf/busybox.config .config
		patch -p1 < /build/conf/busybox_ncurses.patch
		make -j$(nproc)
		make install
		cp _install/bin/busybox $sysroot/bin
		find _install -type l -printf "%f\n" > $sysroot/busybox_applets
		rm -r _install
	fi
}

build_efivar() {
	version=39
	url=https://github.com/rhboot/efivar.git

	cd /build/src
	[ -d efivar-$version ] && rm -rf efivar-$version

	git clone $url efivar-$version
	cd efivar-$version
	git checkout $version
	make CROSS_COMPILE=x86_64-linux-musl- \
		CFLAGS="--sysroot=$sysroot" -j$(nproc)
	make prefix=$sysroot install
}

build_popt() {
	version=1.19
	url=https://github.com/rpm-software-management/popt.git

	cd /build/src
	[ -d popt-$version ] && rm -rf popt-$version

	git clone $url popt-$version
	cd popt-$version
	git checkout popt-$version-release
	./autogen.sh
	./configure --prefix=$sysroot --host=x86_64-linux-musl
	make -j$(nproc)
	make install
}

build_efibootmgr() {
	build_efivar
	build_popt

	version=18
	url=https://github.com/rhboot/efibootmgr.git

	cd /build/src
	[ -d efibootmgr-$version ] && rm -rf efibootmgr-$version

	git clone $url efibootmgr-$version
	cd efibootmgr-$version
	git checkout $version
	export EFIDIR=/boot
	ln -sf /usr/bin/pkg-config $sysroot/bin/x86_64-linux-musl-pkg-config
	make CROSS_COMPILE=x86_64-linux-musl- \
		CFLAGS="--sysroot=$sysroot -I=/include/efivar" -j$(nproc)
	make prefix=$sysroot install
}

build_ncurses() {
	version=6.5
	url=https://invisible-island.net/archives/ncurses
	archive=ncurses-$version.tar.gz
	sig=$archive.asc
	pubkey=19882D92DDA4C400C22C0D56CC2AF4472167BE03
	dir=${archive%.tar.gz}

	cd /build/src
	[ -d $dir ] && rm -rf $dir

	download $url/$archive $url/$sig
	gpg_verify download/$archive download/$sig $pubkey
	tar -xf download/$archive
	cd $dir
	./configure --prefix=$sysroot --with-shared --without-manpages \
		--host=x86_64-linux-musl CFLAGS="--sysroot=$sysroot"
	make -j$(nproc)
	make install
}

build_fdisk() {
	build_ncurses

	version=2.41.2
	url=https://github.com/util-linux/util-linux/archive/refs/tags
	archive=v$version.tar.gz
	dir=util-linux-$version

	cd /build/src
	[ -d $dir ] && rm -rf $dir

	download $url/$archive
	tar -xf download/$archive
	cd $dir
	./autogen.sh
	./configure --prefix=$sysroot --disable-all-programs \
		--enable-fdisks --enable-libfdisk --enable-libuuid --enable-libsmartcols \
		--host=x86_64-linux-musl CFLAGS="--sysroot=$sysroot -L=/lib"
	make -j$(nproc) fdisk
	make install
}

build_e2fsprogs() {
	version=1.47.2
	url=https://github.com/tytso/e2fsprogs/archive/refs/tags
	archive=v$version.tar.gz
	dir=e2fsprogs-$version

	cd /build/src
	[ -d $dir ] && rm -rf $dir

	download $url/$archive
	tar -xf download/$archive
	cd $dir
	mkdir build; cd build
	# libuuid is provided by util-linux
	../configure --prefix=$sysroot --enable-elf-shlibs --disable-libuuid \
		--host=x86_64-linux-musl CFLAGS="--sysroot=$sysroot"
	make -j$(nproc)
	make install
}

build_libnl() {
	version=3.11.0
	url=https://github.com/thom311/libnl/releases/download/libnl${version//./_}
	archive=libnl-$version.tar.gz
	sig=$archive.sig
	pubkey=49EA7C670E0850E7419514F629C2366E4DFC5728
	dir=${archive%.tar.gz}

	cd /build/src
	download $url/$archive $url/$sig
	gpg_verify download/$archive download/$sig $pubkey
	[ -d $dir ] && rm -rf $dir
	tar -xf download/$archive

	cd $dir
	./configure --prefix=$sysroot --host=x86_64-linux-musl --with-sysroot=$sysroot
	make -j$(nproc)
	make install
}

build_wpa_supplicant() {
	build_libnl

	version=2.11
	url=http://w1.fi/releases
	archive=wpa_supplicant-$version.tar.gz
	sig=$archive.asc
	pubkey=EC4AA0A991A5F2464582D52D2B6EF432EFC895FA
	dir=${archive%.tar.gz}

	cd /build/src
	download $url/$archive $url/$sig
	gpg_verify download/$archive download/$sig $pubkey
	[ -d $dir ] && rm -rf $dir
	tar -xf download/$archive

	cd $dir/wpa_supplicant
	sed "s|\$sysroot|$sysroot|" /build/conf/wpa_supplicant.config > .config
	export PKG_CONFIG_PATH=$sysroot/lib/pkgconfig
	make -j$(nproc)
	cp wpa_supplicant $sysroot/bin
}

build_dropbear() {
	version=2025.89
	url=https://dropbear.nl/mirror
	archive=dropbear-$version.tar.bz2
	sig=$archive.asc
	pubkey=F7347EF2EE2E07A267628CA944931494F29C6773
	dir=${archive%.tar.bz2}

	cd /build/src
	download $url/$archive $url/$sig
	gpg_verify download/$archive download/$sig $pubkey
	[ -d $dir ] && rm -rf $dir
	tar -xf download/$archive

	cd $dir
	./configure --prefix=$sysroot --disable-zlib \
		--disable-lastlog --disable-utmp --disable-wtmp \
		--host=x86_64-linux-musl CFLAGS="-Os -W -Wall --sysroot=$sysroot"
	make PROGRAMS="dropbear dropbearconvert" -j$(nproc)
	cp dropbear dropbearconvert $sysroot/bin
}

# stage 1 runs outside chroot, stage 2 runs inside chroot
# both stages run with root permissions

build_ramfs_stage1() {
	ramfs_dir=$base_dir/src/$ramfs

	echo "Running stage 1"

	[ -d $ramfs_dir ] && rm -r $ramfs_dir
	mkdir -p $ramfs_dir/usr/{bin,lib} $ramfs_dir/{proc,sys,dev,etc,var/log,new_root}
	ln -s usr/bin $ramfs_dir
	ln -s usr/lib $ramfs_dir
	ln -s libc.so $ramfs_dir/lib/ld-musl-x86_64.so.1

	cp -Pr /lib/firmware $ramfs_dir/lib
	install -Dt $ramfs_dir/etc/dropbear /etc/ssh/ssh_host_*_key
	install -m600 -Dt $ramfs_dir/home/joe/.ssh /home/joe/.ssh/authorized_keys
	chown -R 1000:1000 $ramfs_dir/home/joe
}

build_ramfs_stage2() {
	ramfs_dir=/build/src/$ramfs

	echo "Running stage 2"

	# busybox
	install -m4755 $sysroot/bin/busybox $ramfs_dir/bin
	while read link; do ln -s busybox $ramfs_dir/bin/$link; done < $sysroot/busybox_applets

	# efibootmgr
	bininst efibootmgr

	# fdisk
	bininst fdisk

	# e2fsprogs
	bininst e2label fsck fsck.ext4 mkfs.ext4 resize2fs tune2fs blkid

	# wpa_supplicant
	bininst wpa_supplicant
	cp /build/conf/wpa_supplicant.conf $ramfs_dir/etc

	# user infrastructure for dropbear
	passwd=$(cat /build/conf/ramfs_password)
	touch $ramfs_dir/etc/shadow; chmod 600 $ramfs_dir/etc/shadow
	groupadd -R $ramfs_dir -g0 root
	useradd -R $ramfs_dir -p "$passwd" -u0 -g0 -d /root -s /bin/sh root
	groupadd -R $ramfs_dir -g1000 joe
	useradd -R $ramfs_dir -u1000 -g1000 -s /bin/sh -m joe
	rm $ramfs_dir/etc/*- $ramfs_dir/etc/.pwd.lock

	# dropbear
	for key in $ramfs_dir/etc/dropbear/ssh_host_*_key; do
		$sysroot/lib/ld-musl-x86_64.so.1 $sysroot/bin/dropbearconvert openssh dropbear \
			$key $(echo $key | sed -E 's/ssh_host_(.*)_key/dropbear_\1_host_key/')
		rm $key
	done
	bininst dropbear

	cp /build/conf/init $ramfs_dir
	cp /build/conf/inittab $ramfs_dir/etc
	cp /build/conf/resolv.conf $ramfs_dir/etc
	cp /build/conf/netsetup $ramfs_dir/bin
	cp /build/conf/procs $ramfs_dir/bin

	cd $ramfs_dir; find . | cpio -o -H newc | gzip > /build/src/$ramfs.img
}

[ $# -lt 1 ] && usage

base_dir=$(dirname $0)/..
sysroot=/build/sysroot
ramfs=initramfs

case "$1" in
	musl | busybox | efibootmgr | fdisk | e2fsprogs | wpa_supplicant | dropbear | ramfs_stage2)
		[ $0 = "/build/scripts/build" ] || exec $base_dir/scripts/chroot /build/scripts/build $@
		func=build_$1
		shift
		$func $@
		;;
	ramfs)
		if [ $(whoami) != "root" ]; then
			echo "Error: building ramfs requires root permissions"
			exit 1
		fi
		build_ramfs_stage1
		exec $0 ramfs_stage2
		;;
	*)
		echo "$1: not a valid build target"
		;;
esac
