#!/bin/sh

if [ -z "$UNSHARE" ]; then
	export UNSHARE=1
	if [ $(whoami) = "root" ]; then
		exec unshare --mount $0 "$@"
	else
		exec unshare --mount --map-root-user $0 "$@"
	fi
fi

base_dir=$(dirname $0)/..
rootfs=$base_dir/buildroot

for m in /proc /sys /dev; do
	mount --rbind $m $rootfs/$m
done

for m in src conf scripts; do
	mkdir -p $rootfs/build/$m
	mount --bind $base_dir/$m $rootfs/build/$m
done

export sysroot=/build/sysroot
export PATH=$PATH:$sysroot/bin
export PKG_CONFIG_PATH=$sysroot/lib/pkgconfig
export HOME=/root
export TAR_OPTIONS="--no-same-owner"

chroot $rootfs "$@"
ret=$?

# unmounting not needed as new mountpoints are automatically destroyed
# as soon as we leave the mount namespace

[ $ret -ne 0 ] && echo "chroot: exit status $ret"
exit $ret
