#!/bin/sh

set -e

url=https://repo-default.voidlinux.org/live/current
archive=void-x86_64-ROOTFS-20250202.tar.xz
sums=sha256sum.txt
sig=sha256sum.sig
pubkey=/usr/share/void-release-keys/void-release-20250202.pub
rootfs=buildroot

cd $(dirname $0)/..

if [ ! -f $archive -o -f $sums ]; then
	curl -LO $url/$archive
	curl -LO $url/$sums
	curl -LO $url/$sig
	minisign -V -p $pubkey -x $sig -m $sums
	sum_good=$(awk -v name=$archive '$2 == "("name")" {print $4}' $sums)
	sum=$(sha256sum $archive | awk '{print $1}')
	if [ "$sum" != "$sum_good" ]; then
		echo "Error: $archive: checksum does not match!"
		exit 1
	fi
	rm $sums $sig
fi

packages="gcc make pkg-config wget curl git gnupg patch
	ncurses-devel foot-terminfo cpio lz4 xz
	automake autoconf gettext-devel-tools libtool
	bison flex wpa_supplicant"

mkdir -p $rootfs
tar -xf $archive -C $rootfs

cp conf/resolv.conf $rootfs/etc
cat > $rootfs/root/.bashrc <<-EOF
	alias ls='ls --color'
	export PS1='\[\e[1;38;5;3m\]build-chroot \[\e[1;38;5;4m\]\w \[\e[0m\]\\$ '
EOF

scripts/chroot sh <<-EOF
	xbps-install -Suy xbps
	xbps-install -uy
	xbps-install -y $(echo $packages)
EOF
