#!/bin/sh

set -e

base_dir=$(dirname $0)/..

read -r -p "Enter SSID: " ssid
read -r -p "Enter passphrase: " pass
$base_dir/scripts/chroot wpa_passphrase "$ssid" "$pass" |
	grep -v '#psk' > $base_dir/conf/wpa_supplicant.conf
echo "Successfully stored network configuration in conf/wpa_supplicant.conf"
