#!/bin/sh

set -e

base_dir=$(dirname $0)/..

echo "Setting new password for root user in initramfs"
read -rsp "Enter password: " passwd
echo $passwd | openssl passwd -6 -stdin > $base_dir/conf/ramfs_password
echo -e "\nSuccessfully updated password"
